# Generated by Django 6.0.6 on 2026-06-11 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_emp_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_email',
            field=models.EmailField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_phone',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
